<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Projet;
use AppBundle\Entity\Compta;
use AppBundle\AppBundle;

/**
 * ComptaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptaRepository extends \Doctrine\ORM\EntityRepository
{

    public function conso(Projet $projet, $annee)
    /* Renvoie les données de conso d'un projet sur une année
     * On ne s'intéresse qu'aux lignes de type 2, c'est-à-dire "group"
     * Les données de type 1 (user) sont ignorées
     * On ne s'intéresse qu'aux ressources 'cpu' ou 'gpu'
     */
    {
        $debut = new \DateTime( $annee . '-01-01');
        $fin   = new \DateTime( $annee . '-12-31');
        
        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c
            FROM AppBundle:Compta c
            WHERE c.loginname = :loginname
            AND c.type = 2
            AND c.date >= :debut
            AND c.date <= :fin
            AND (c.ressource = \'cpu\' OR c.ressource = \'gpu\')
            ORDER BY c.date ASC'
        )
        ->setParameter('loginname', lcfirst($projet->getIdProjet() ) )
        ->setParameter('debut',$debut)
        ->setParameter('fin',$fin)
        ->getResult();            

        if( $db_data == null || empty( $db_data ) ) return null;
                        
        return $db_data;
    }
    
    public function consoTotale($annee)
    /* Renvoie les données de conso de la somme de tous les types 2 cpu, tous les Type 2 gpu, etc.
     * Se limite aux projets P* et T* (exclusion des projets E*)
     */
    {
        $debut = new \DateTime( $annee . '-01-01');
        $fin   = new \DateTime( $annee . '-12-31');
        
        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c.date,c.ressource,sum(c.conso) AS conso
             FROM AppBundle:Compta c 
             WHERE c.type = 2
             AND c.date >= :debut
	     AND c.date <= :fin
	     AND ( c.loginname LIKE \'p%\' OR c.loginname LIKE \'t%\' )
             GROUP BY c.date,c.ressource'
        )
        ->setParameter('debut',$debut)
        ->setParameter('fin',$fin)
        ->getResult();

        if( $db_data == null || empty( $db_data ) ) return null;
                        
        return $db_data;

    }
}
