<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Projet;
use AppBundle\Entity\Compta;
use AppBundle\AppBundle;

/**
 * ComptaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptaRepository extends \Doctrine\ORM\EntityRepository
{

	/* -------- FONCTIONS DE HAUT NIVEAU -------- */
	
    public function conso(Projet $projet, $annee)
    /* Renvoie les données de conso d'un projet sur une année
     * On ne s'intéresse qu'aux lignes de type 2, c'est-à-dire "group"
     * On ne s'intéresse qu'aux ressources de type calcul, c-à-d cpu, gpu
     * Les données de type 1 (user) sont ignorées
     */
    {
        $debut = new \DateTime( $annee . '-01-01');
        $fin   = new \DateTime( $annee . '-12-31');

        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c
            FROM AppBundle:Compta c
            WHERE c.loginname = :loginname
            AND (c.ressource = \'cpu\' OR c.ressource=\'gpu\')
            AND c.type = 2
            AND c.date >= :debut
            AND c.date <= :fin
            ORDER BY c.date ASC'
        )
        ->setParameter('loginname', lcfirst($projet->getIdProjet() ) )
        ->setParameter('debut',$debut)
        ->setParameter('fin',$fin)
        ->getResult();

        if( $db_data == null || empty( $db_data ) ) return null;

        return $db_data;
    }

    public function consoDateInt(Projet $projet, \DateTime $date)
    /* Renvoie les données de conso d'un projet à une date donnée
     * On ne s'intéresse qu'aux lignes de type 2, c'est-à-dire "group"
     * On ne s'intéresse qu'aux ressources de type calcul, c-à-d cpu, gpu
     * Les données de type 1 (user) sont ignorées
     * Renvoie un int
     */
    {
		$conso_cpu = $this->consoResPrjDate($projet, ['ress' => 'cpu'], $date);
		////echo('<pre>'.$projet."###".$date->format('Y-m-d').'</pre>');
		////echo ('<pre>cpu = ');print_r($conso_cpu); echo('</pre>');
		if ($conso_cpu == null)
		{
			$cpu = 0;
		}
		else
		{
			$cpu = intval($conso_cpu[0]->getConso());
		}
		
		$conso_gpu = $this->consoResPrjDate($projet, ['ress' => 'gpu'], $date);
		////echo ('<pre>gpu =');print_r($conso_gpu);echo('</pre>');
		if ($conso_gpu == null)
		{
			$gpu = 0;
		}
		else
		{
			$gpu = intval($conso_gpu[0]->getConso());
		}
		return $cpu + $gpu;
	}

    public function consoTotale($annee,$ressource)
    /* Renvoie les données de conso de la somme de tous les types 2 de la ressource spécifiée
     * Se limite aux projets P* et T* (exclusion des projets E*)
     */
    {
        $debut = new \DateTime( $annee . '-01-01');
        $fin   = new \DateTime( $annee . '-12-31');

        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c.date,c.ressource,sum(c.conso) AS conso
             FROM AppBundle:Compta c
             WHERE c.type = 2
             AND c.date >= :debut
	         AND c.date <= :fin
	         AND c.ressource = :ressource
	         AND ( c.loginname LIKE \'p%\' OR c.loginname LIKE \'t%\' )
             GROUP BY c.date'
        )
        ->setParameter('debut',$debut)
        ->setParameter('fin',$fin)
        ->setParameter('ressource',$ressource)
        ->getResult();

        if( $db_data == null || empty( $db_data ) ) return null;

        return $db_data;

    }

	/* -------- FONCTIONS DE BAS NIVEAU -------- */

    /******************
    * Retourne les données de compta pour un projet, une ressource, une année
    *
    *      params: $projet
    *              $ressource Un tableau décrivant une ressource (cf. parameters.yml)
    *              $annee     Une annee
    *
    *      Retourne: Un tableau d'objets Compta
    *
    *********************/
    public function consoResPrj(Projet $projet, $ressource, $annee)
    {
        $debut = new \DateTime( $annee . '-01-01');
        $fin   = new \DateTime( $annee . '-12-31');

        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c
            FROM AppBundle:Compta c
            WHERE c.loginname = :projet
            AND   c.type=2
            AND   c.ressource = :res
            AND   c.date >= :debut
            AND   c.date <= :fin
            ORDER BY c.date ASC'
        )
        ->setParameter ('projet', strtolower($projet->getIdProjet() ) )
        ->setParameter ('debut',$debut)
        ->setParameter ('res', $ressource['ress'])
        ->setParameter ('fin',$fin)
        ->getResult();

		if( $db_data == null || empty( $db_data ) ) return null;
        return $db_data;
	}

    /******************
    * Retourne les données de compta pour un projet, une ressource, une date
    *
    *      params: $projet
    *              $ressource Un tableau décrivant une ressource (cf. parameters.yml)
    *              $date      Une date
    *
    *      Retourne: objet Compta
    *
    *********************/
    public function consoResPrjDate(Projet $projet, $ressource, \Datetime $date)
    {
		////echo('<pre>#'.strtolower($projet->getIdProjet())."#".$date->format('Y-m-d')."#".$ressource['ress']."#</pre>");
		//echo('<pre>#--->'.$projet->getIdProjet()."#".print_r($ressource)."#".$date->format('Y-m-d').'</pre>');
        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c
            FROM AppBundle:Compta c
            WHERE c.loginname = :projet
            AND   c.type=2
            AND   c.ressource = :res
            AND   c.date = :date'
        )
        //->setParameter ('projet', strtolower($projet->getIdProjet() ) )
        ->setParameter ('projet', $projet)
        ->setParameter ('date',$date)
        ->setParameter ('res', $ressource['ress'])
        ->getResult();

		////echo('<pre>'.print_r($db_data,true).'</pre>');
		if( $db_data == null || empty( $db_data ) ) return null;
        return $db_data;
	}

    /* Renvoie les données de compta pour un projet OU un user, une ressource, une année */
    public function consoResPrjUser(Projet $projet, $user, $ressource, $annee)
    {
        $debut = new \DateTime( $annee . '-01-01');
        $fin   = new \DateTime( $annee . '-12-31');

        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c
            FROM AppBundle:Compta c
            WHERE ((c.loginname = :projet AND c.type=2) OR (c.loginname = :login AND c.type=1))
            AND     c.ressource = :res
            AND c.date >= :debut
            AND c.date <= :fin
            ORDER BY c.date ASC'
        )
        ->setParameter ('loginname', $user )
        ->setParameter ('projet', strtolower($projet->getIdProjet() ) )
        ->setParameter ('debut',$debut)
        ->setParameter ('res', $ressource['nom'])
        ->setParameter ('fin',$fin)
        ->getResult();

		if( $db_data == null || empty( $db_data ) ) return null;
        return $db_data;
	}

    /* Renvoie la conso cpu (!) d'un projet à une date donnée, éventuellement renvoie null
     * Peut être utile dans des fixtures de temps en temps
     */
    public function consoDateProjet(Projet $projet, \DateTime $date)
    {
        $db_data = AppBundle::getManager()->createQuery(
            'SELECT c
            FROM AppBundle:Compta c
            WHERE c.loginname = :loginname
            AND c.type = 2
            AND c.date = :date'
        )
        ->setParameter('loginname', lcfirst($projet->getIdProjet() ) )
        ->setParameter('date',$date)
        ->getResult();

        if( $db_data == null || empty( $db_data ) ) return null;

        return $db_data;
    }

}
