<?php

/**
 * This file is part of GRAMC (Computing Ressource Granting Software)
 * GRAMC stands for : Gestion des Ressources et de leurs Attributions pour Mésocentre de Calcul
 *
 * GRAMC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 *  GRAMC is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GRAMC.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  authors : Miloslav Grundmann - C.N.R.S. - UMS 3667 - CALMIP
 *            Emmanuel Courcelle - C.N.R.S. - UMS 3667 - CALMIP
 *            Nicolas Renon - Université Paul Sabatier - CALMIP
 **/

namespace AppBundle\Repository;

use AppBundle\Entity\Projet;
use AppBundle\Utils\GramcDate;


/**
 * ConsommationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsommationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getConsommation(Projet $projet, $annee = null)
    {
        if( $annee == null ) $annee = GramcDate::get()->showYear();

        return $this->getEntityManager()
         ->createQuery
        ('SELECT c FROM AppBundle:Consommation c WHERE ( c.annee = :annee AND c.projet = :idProjet)')
        ->setParameter('idProjet', $projet->getIdProjet() )
        ->setParameter('annee', $annee )
        ->getOneOrNullResult();
    }

   

}
