<?php

/**
 * This file is part of GRAMC (Computing Ressource Granting Software)
 * GRAMC stands for : Gestion des Ressources et de leurs Attributions pour Mésocentre de Calcul
 *
 * GRAMC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 *  GRAMC is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GRAMC.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  authors : Miloslav Grundmann - C.N.R.S. - UMS 3667 - CALMIP
 *            Emmanuel Courcelle - C.N.R.S. - UMS 3667 - CALMIP
 *            Nicolas Renon - Université Paul Sabatier - CALMIP
 **/

namespace AppBundle\Repository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findData(\DateTime $debut, \DateTime $fin, $niveau)
    {        
            return $this->getEntityManager()
                   ->createQuery('SELECT j FROM AppBundle:Journal j WHERE ( j.stamp <= :fin AND j.stamp >= :debut AND j.niveau <= :niveau) ORDER BY j.stamp DESC ')
                   ->setParameter('fin', $fin)
                   ->setParameter('debut', $debut)
                   ->setParameter('niveau', $niveau)
                   ->getResult();
    }

    public function liste_avant($date)
    {
            return $this->getEntityManager()
            ->createQuery("SELECT j FROM AppBundle:Journal j WHERE j.stamp <= :date")
            ->setParameter('date', $date )
            ->getResult();
       
    }
}
